# 端口
server:
  port: 20001

spring:
  application:
    name: gateway
  config:
    import:
      - optional:nacos:${spring.application.name}
  cloud:
#    inetutils:
#      preferred-networks: 192.168,10.0,172.16  # 优先 IPv4
    nacos:
      discovery:
        server-addr: 192.168.1.152:8848   # Nacos 地址
        username: nacos                   # 默认账号
        password: nacos                   # 默认密码
        namespace: 0de7e8a0-5088-422a-8aa9-c172e46241f1        # 命名空间
      config:
        server-addr: 192.168.1.152:8848   # Nacos 地址
        username: nacos                   # 默认账号
        password: nacos                   # 默认密码
        namespace: 0de7e8a0-5088-422a-8aa9-c172e46241f1
        file-extension: yaml              # 配置内容文件的数据格式，默认值：properties
        group: DEFAULT_GROUP
        refresh-enabled: true  # 可选：启用动态刷新
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
          # 使用小写service-id
          lower-case-service-id: true

logging:
  level:
    root: debug
  path: /data/logs


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true


