
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
